### ISSUE TITLE
Fix login.html issues

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#1]
Recheck all login page styles and make it looks as in the design spec provided.
Particularly:

1. Fix incorrect modal width and height
2. Fix incorrect fonts for modal header, text input labels and primary button
3. Change icons to correct ones. Correct icons are available here
4. Fix incorrect text inputs sizes, paddings and fonts according to design files
5. Make overlay blurred:
![1](https://user-images.githubusercontent.com/9034705/28568305-048b118a-713e-11e7-833c-dc5bff0988f6.png)

**Comment by snovikov-gd** [comment]
@etuseeva-gd 
- ‘PT Sans’ is used for primary button though ‘PT Sans Caption’ must be (2)

**Comment by etuseeva** [comment]
resolve

**Comment by snovikov-gd** [comment]
Confirmed
