### ISSUE TITLE
[Global] Separate your modules

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#10]
Separate all your code to 2 modules - `/js/image-slider` and `/js/add-review`. You can create also module initialization script file or just put initialization code at the botton of `product-admin.html`, like:

```
ImageSlider.init('.image-slider')
AddReview.init('.add-review')
```

**Comment by etuseeva** [comment]
Resolve

**Comment by snovikov-gd** [comment]
Resolved, closed
