### ISSUE TITLE
[Product Image Slider] Get rid of hardcoded images values

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#13]
Get rid of productImageObjects hardcode. Get such data directly from `<img>` you put in the markup. It can be `src` and `alt` attributes.
It must be possible to easily add / change images and its descriptions touching just markup, not javascript sources.

https://github.com/etuseeva-gd/grid-u-angular2/blob/b86d765b48c8576a453a6a1a1a4668511e3aa60e/js/index.js#L170-L175

**Comment by etuseeva** [comment]
resolve

**Comment by snovikov-gd** [comment]
Resolved, closed
