### ISSUE TITLE
[Product Image Slider] Rename ImageForSlider class

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#17]
https://github.com/etuseeva-gd/grid-u-angular2/blob/b86d765b48c8576a453a6a1a1a4668511e3aa60e/ts/index.ts#L21

Rename to `ImageForSlider` cause it is a constructor returning a single instance not array

**Comment by etuseeva** [comment]
resolve

**Comment by snovikov-gd** [comment]
Resolved, closed
