### ISSUE TITLE
[Product Image Slider] Make `getSidePosition` static

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#18]
Make `.getSidePosition()` method static

https://github.com/etuseeva-gd/grid-u-angular2/blob/b86d765b48c8576a453a6a1a1a4668511e3aa60e/ts/index.ts#L102-L105

**Comment by etuseeva** [comment]
resolve

**Comment by snovikov-gd** [comment]
Resolved, closed
