### ISSUE TITLE
[Add Review] Refactor toggleReview()

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#19]
Make 'Add Review' togglable just by toggling module container class name

https://github.com/etuseeva-gd/grid-u-angular2/blob/b86d765b48c8576a453a6a1a1a4668511e3aa60e/ts/index.ts#L423-L441

**Comment by etuseeva** [comment]
resolve

**Comment by snovikov-gd** [comment]
Resolved, closed
