### ISSUE TITLE
Fix main.html issues

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#2]
1. Fix incorrect font families and font sizes everywhere

2. Fix incorrect content wrapper width:
![2](https://user-images.githubusercontent.com/9034705/28568822-e24b9318-713f-11e7-99e6-a2d9a34a5fd9.png)

3. Fix incorrect cart and logout icons in header. Correct icons are available here

4. Fix incorrect filter text input styles:
![3](https://user-images.githubusercontent.com/9034705/28568834-f1bc5c24-713f-11e7-8cf6-193cde95b4aa.png)

5. Currently the result looks too different from the design spec. Fix filter bar according to design specs. Recheck all the sizes, paddings, etc. Fix also next issues:
a. Button must look pressed when filters are opened
b. Fix triangle positioning
c. Fix down arrow icon appearance and positioning:
![4](https://user-images.githubusercontent.com/9034705/28568860-090fecce-7140-11e7-9758-3f8f3385a230.png)
d. Eliminate all issues connected with opening filters and clicking on elements. Currently filters are hiding when clicks on any input inside it.

6. Apply gradient to header according to design specs

7. Username in header must be emphasized according to design specs

**Comment by snovikov-gd** [comment]
@etuseeva-gd 
- search icon is missing (4)
- down arrow icon is too big (5d)

**Comment by etuseeva** [comment]
resolve (search icon isn't missing)

**Comment by snovikov-gd** [comment]
Confirmed
