### ISSUE TITLE
Platform-browser

### ISSUE THREAD

**Issue by ghost** [etuseeva-gd/grid-u-angular2#20]
Not an Issue, just a nitpick. 
In production usually it's a good idea to use platform-browser instead of platform-browser-dynamic.
https://github.com/etuseeva-gd/grid-u-angular2/blob/02ca1d75965d2e9f67fe5b6dbc75dde717b6b880/demo-shop/src/main.ts#L2

**Comment by etuseeva** [comment]
Ok. Do I need to do this in this project?

**Comment by ghost** [comment]
No need, just for reference
