### ISSUE TITLE
Use classes instead of Interfaces

### ISSUE THREAD

**Issue by ghost** [etuseeva-gd/grid-u-angular2#21]
Just fyi, not necessary to change anything here, since it can be a big change.
Interfaces are fine, but when projects gets bigger using them quickly becomes cumbersome, classes usually a better choice, since you can create default values and so on.

https://github.com/etuseeva-gd/grid-u-angular2/blob/02ca1d75965d2e9f67fe5b6dbc75dde717b6b880/demo-shop/src/app/models.ts#L1-L5

**Comment by etuseeva** [comment]
Ok
