### ISSUE TITLE
Brackets in switch

### ISSUE THREAD

**Issue by ghost** [etuseeva-gd/grid-u-angular2#22]
Most linters won't allow {} in case statements

https://github.com/etuseeva-gd/grid-u-angular2/blob/02ca1d75965d2e9f67fe5b6dbc75dde717b6b880/demo-shop/src/app/services/error-handler.service.ts#L16-L29

**Comment by etuseeva** [comment]
Fixed

**Comment by ghost** [comment]
Well i was talking about removing all the brackets inside case statements, but thats mostly a style issue. closed
