### ISSUE TITLE
ngrx actions

### ISSUE THREAD

**Issue by ghost** [etuseeva-gd/grid-u-angular2#23]
For readability it's better to use Typed Actions https://github.com/ngrx/platform/blob/master/docs/store/actions.md#typed-actions

https://github.com/etuseeva-gd/grid-u-angular2/blob/02ca1d75965d2e9f67fe5b6dbc75dde717b6b880/demo-shop/src/app/services/product.service.ts#L20-L27

**Comment by etuseeva** [comment]
Fixed
