### ISSUE TITLE
ngrx and rxjs stores

### ISSUE THREAD

**Issue by ghost** [etuseeva-gd/grid-u-angular2#24]
I can see that you use both rxjs stores and ngrx stores, it can get really confusing i suggest to stick to one way of state management, whichever you prefer most

(GitHub bugged out on me i can't paste code for some reason)
https://github.com/etuseeva-gd/grid-u-angular2/blob/master/demo-shop/src/app/services/category.service.ts#L9-L13

**Comment by etuseeva** [comment]
fixed
