### ISSUE TITLE
DEFAULT_IMAGE and some nitpicks

### ISSUE THREAD

**Issue by ghost** [etuseeva-gd/grid-u-angular2#25]
I can see that every component that uses this directive have to pass same DEFAULT_IMAGE, why not just set it as a constant in this directive. 
Also i found that writing one-line functions in template directly is usually more convenient, unless it's repeated multiple times or hard to read.
PS no need to write empty constructor or ngOnInit functions, i could see in multiple places

https://github.com/etuseeva-gd/grid-u-angular2/blob/02ca1d75965d2e9f67fe5b6dbc75dde717b6b880/demo-shop/src/app/directives/default-image.directive.ts#L14-L21

**Comment by etuseeva** [comment]
Maybe in the future, when need to set another image. Deleted now
