### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ghost** [etuseeva-gd/grid-u-angular2#28]
I don't see any issues from Angular 2 point of view, good job!

Most of my issues are style recommendations, apart from using classes instead of interfaces and mixing ngRx and rxjs Subjects as a state management tool, better to stick to one.

Also would be great to see an example of unit tests, at least for one component. Unit tests are a big part of angular 2 development and it has a lot of special tooling for this(TestBed etc).

**Comment by etuseeva** [comment]
Thanks! 
What should tests check? Work with back-end (logic), texts in html or something else?

**Comment by ghost** [comment]
Just pick one component and one service for example. And just create simple unit test for methods and for template logic(*ngIfs, *ngFors etc). Quality of test don't really matter to me it's mostly about setting up a test

**Comment by etuseeva** [comment]
Wrote simple tests for component and service:
https://github.com/etuseeva-gd/grid-u-angular2/tree/master/demo-shop/src/tests

**Comment by ghost** [comment]
Thanks, lgtm.
