### ISSUE TITLE
Fix product_customer.html

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#3]
1. Fix all fonts issues. Fonts must look according to design spec

2. Fix incorrect content wrapper width:
![5](https://user-images.githubusercontent.com/9034705/28568953-54115032-7140-11e7-8fb3-b1ae0fbba511.png)

**Comment by etuseeva** [comment]
resolve (change font-size in description block)

**Comment by snovikov-gd** [comment]
Confirmed
