### ISSUE TITLE
Fix product_admin.html issues

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#4]
1. Fix all fonts issues. Fonts must look according to design spec

2. Center all modals

3. Increase margins between these buttons according to design specs:
![6](https://user-images.githubusercontent.com/9034705/28568983-7e21f57a-7140-11e7-9461-3deb95c2e5c4.png)

4. Apply all applicable fixes mentioned above(recheck sizes, paddings, fonts etc).

**Comment by snovikov-gd** [comment]
@etuseeva-gd 
- fix incorrect font size for product description block (1)

**Comment by etuseeva** [comment]
resolve

**Comment by snovikov-gd** [comment]
Confirmed
