### ISSUE TITLE
Replace clearfix nodes to pseudoelements

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#5]
1. Replace all `<div class="clearfix"></div>` usages to `::before` or `::after`
2. Read about any CSS methodology. I’d recommend BEM intro. Because this is the way to Hell:
![05](https://user-images.githubusercontent.com/9034705/28569249-c2028e84-7141-11e7-9d5c-f611a5f096aa.png)

**Comment by etuseeva** [comment]
resolve

**Comment by snovikov-gd** [comment]
Confirmed
