### ISSUE TITLE
Fix main.html issues

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#6]
1. Center cart icon vertically relatively(more accurately than now):
![01](https://user-images.githubusercontent.com/9034705/28569336-0b5f4aa4-7142-11e7-969e-a24bfa4c8e83.png)

2. Get rid of jQuery matchHeight plugin. Use flexbox to provide the same height for these block instead:
![02](https://user-images.githubusercontent.com/9034705/28569343-14853238-7142-11e7-91d4-96842e41c3f2.png)

**Comment by etuseeva** [comment]
resolve

**Comment by snovikov-gd** [comment]
Confirmed
