### ISSUE TITLE
Fix login.html issues

### ISSUE THREAD

**Issue by snovikov-gd** [etuseeva-gd/grid-u-angular2#7]
1. Get rid of <img> with icons: place input component-related icons to input:focus styles as you did for box-shadow:
![03](https://user-images.githubusercontent.com/9034705/28569375-31566512-7142-11e7-9c30-572d8af14a37.png)

2. Add ‘for’ attribute for labels since they do not wrap input fields so, in fact, they do not work now.

3. Fix text input overflow issue:
![04](https://user-images.githubusercontent.com/9034705/28569386-392fa816-7142-11e7-8f37-0335e0320451.png)

FYI: transform: `translate(-50%, 0);` centering causes visual issues when modal width is odd number(e.g. 555px / 2 = 277.5px). It’s better to use flexbox centering when possible.

**Comment by etuseeva** [comment]
resolve

**Comment by snovikov-gd** [comment]
Confirmed
